run:
  deadline: 5m
  tests: true
  modules-download-mode: vendor
  skip-dirs:
  - vendor
  - generated
  build-tags: []

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
  - golint
  - errcheck
  - misspell
  - deadcode
  - govet
  - typecheck
  - lll
  - megacheck
  - varcheck
  - unconvert
  - bodyclose
  - scopelint
  - goimports
  - ineffassign
  - gofmt
  - maligned
  - goconst
  - gocyclo
  - unparam
  - structcheck
  - staticcheck
  - gocritic

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  misspell:
    locale: US
  unused:
    check-exported: false
  gocyclo:
    min-complexity: 30
  goimports:
    local-prefixes: arhat.dev/template-kubernetes-controller
  lll:
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 4
  maligned:
    suggest-new: true

issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - gocyclo
    - errcheck
    - dupl
    - gosec
    - maligned
    - lll
    - scopelint

  - path: pkg/apis
    linters:
    - lll
