apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template-kubernetes-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template-kubernetes-controller.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "template-kubernetes-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "template-kubernetes-controller.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "template-kubernetes-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "template-kubernetes-controller.fullname" . }}
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /template-kubernetes-controller
            - -c
            - /etc/template-kubernetes-controller/config.yaml
          env:
            - name: GODEBUG
              value: madvdontneed=1
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          {{- if and .Values.config.templateKubernetesController.metrics.enabled (ne (include "template-kubernetes-controller.metricsPort" .) "0") }}
          ports:
            - name: metrics
              containerPort: {{ include "template-kubernetes-controller.metricsPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.config.templateKubernetesController.metrics.httpPath | default "/metrics" }}
              port: metrics
          readinessProbe:
            httpGet:
              path: {{ .Values.config.templateKubernetesController.metrics.httpPath | default "/metrics" }}
              port: metrics
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
