{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "template-kubernetes-controller.fullname" . }}:{{ .Release.Namespace }}:discovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:discovery
subjects:
- kind: ServiceAccount
  name: {{ include "template-kubernetes-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "template-kubernetes-controller.fullname" . }}:controller
  namespace: {{ .Release.Namespace }}
rules:
{{- if (contains .Values.config.templateKubernetesController.leaderElection.lock.type "configmaps") }}
- apiGroups: [""]
  resources:
  - configmaps
  verbs:
  - create
  - get
  - update
  - patch
  resourceNames:
  - {{ .Values.config.templateKubernetesController.leaderElection.lock.name | default "template-kubernetes-controller-leader-election" }}
{{- end }}
{{- if (contains .Values.config.templateKubernetesController.leaderElection.lock.type "endpoints") }}
- apiGroups: [""]
  resources:
  - endpoints
  verbs:
  - create
  - get
  - update
  - patch
  resourceNames:
  - {{ .Values.config.templateKubernetesController.leaderElection.lock.name | default "template-kubernetes-controller-leader-election" }}
{{- end }}
{{- if (contains .Values.config.templateKubernetesController.leaderElection.lock.type "leases") }}
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs:
  - create
  - get
  - update
  - patch
  resourceNames:
  - {{ .Values.config.templateKubernetesController.leaderElection.lock.name | default "template-kubernetes-controller-leader-election" }}
{{- end }}
{{- end }}
