name: Label

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
    - master
    - "!deps/**"

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
